package miasi_bank;

/**
 * Created by Tomasz Gwoździk on 23.03.2017.
 */
public enum OperationType {
    PAYMENT, WITHDRAW, TRANSFER, CALCULATE_INTEREST, CHANGE_INTEREST_MECHANISM, CREATE_PLACEMENT, CLOSE_PLACEMENT, CREATE_LOAN, PAY_OFF_LOAN, CREATE_DEBIT, CREATE_RAPORT
}
